baseURL = "http://archive.ragnhildwesenberg.com"
languageName = "En"
languageCode = "en-us"
# post pagination
paginate = "5"
title = "Cellist Ragnhild Wesenberg"

[params]
  author = "Ragnhild Wesenberg"
  sitename = "Cellist Ragnhild Wesenberg"
  description = "Cellist Ragnhild Wesenberg"

[params.homepage.photo]
URL = "images/rghld_main.jpg"

############################# output ##############################
[outputs]
home = [ "HTML", "RSS", "json"]

# render unsafe html
[markup.goldmark.renderer]
unsafe = true

############################# Plugins ##############################
# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]

################################ menu ##################################
[[menu.main]]
name = "Home"
URL = "/"
weight = 1

[[menu.main]]
name = "About"
URL = "/about"
weight = 2

[[menu.main]]
name = "News"
URL = "/news "
weight = 3

[[menu.main]]
name = "Projects"
URL = "/projects"
weight = 4

[[menu.main]]
name = "Contact"
URL = "/contact"
weight = 5

############################# social site ########################
[[params.social]]
title = "facebook"
icon = "ti-facebook" # themify icon : https://themify.me/themify-icons
link = "https://www.facebook.com/Ragnhild-Wesenberg-104607391628140"

[[params.social]]
title = "youtube"
icon = "ti-youtube" # themify icon : https://themify.me/themify-icons
link = "https://www.youtube.com/channel/UCYrGHncH2r-mRB56_zgkhHw"

[[params.social]]
title = "instagram"
icon = "ti-instagram" # themify icon : https://themify.me/themify-icons
link = "https://www.instagram.com/celloragnhild/"

[[params.social]]
title = "linkedin"
icon = "ti-linkedin" # themify icon : https://themify.me/themify-icons
link = "https://www.linkedin.com/in/ragnhild-wesenberg-337ba8203/"
